### ISSUE TITLE
Minimum Stability?

### ISSUE THREAD

**Issue by astorm** [extdn/extension-dashboard-m2#1]
When I was trying to use the installation instructions from the README.md file, I ended up in the following situation

    $ composer require extdn/extension-dashboard-m2
                                                          
                                                              
      [InvalidArgumentException]                                      
      Could not find package extdn/extension-dashboard-m2 at any ver  
      sion for your minimum-stability (beta). Check the package spe  
      lling or your minimum-stability                                 
                                                              

    require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

and I needed to bump my minimum stability all the way down to `dev` in order to get this working.  

I would be nice I hadn't needed to do this.

**Comment by fooman** [comment]
Thanks @astorm indeed it's currently still in development. I updated the [instructions](https://github.com/extdn/extension-dashboard-m2/commit/68154edb3433f4b1fdb70ed2f364a8897ffa95b7) to `composer require extdn/extension-dashboard-m2:dev-master` which only downgrades the stability requirement for this package only.

**Comment by fooman** [comment]
Until such time that a tagged release is available.
