### ISSUE TITLE
Error in composer require on 2.4.1

### ISSUE THREAD

**Issue by rav-redchamps** [extdn/extension-dashboard-m2#3]
Command `composer require extdn/extension-dashboard-m2:dev-master` terminates with error

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - magento/framework 102.0.0 requires php ~7.1.3||~7.2.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 102.0.1 requires php ~7.1.3||~7.2.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 102.0.2 requires php ~7.1.3||~7.2.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - magento/framework 102.0.2-p2 requires php ~7.1.3||~7.2.0 -> your PHP version (7.3.19) does not satisfy that requirement.
    - Installation request for extdn/extension-dashboard-m2 dev-master -> satisfiable by extdn/extension-dashboard-m2[dev-master].
    - Conclusion: remove laminas/laminas-code 3.4.1
    - Conclusion: don't install laminas/laminas-code 3.4.1
    - extdn/extension-dashboard-m2 dev-master requires magento/framework ^102.0.0 -> satisfiable by magento/framework[102.0.6, 102.0.5-p2, 102.0.4-p2, 102.0.5, 102.0.3-p1, 102.0.4, 102.0.2-p2, 102.0.3, 102.0.2, 102.0.1, 102.0.0].
    - magento/framework 102.0.6 requires laminas/laminas-code ~3.3.0 -> satisfiable by laminas/laminas-code[3.3.0, 3.3.1, 3.3.2].
    - magento/framework 102.0.5-p2 requires laminas/laminas-code ~3.3.0 -> satisfiable by laminas/laminas-code[3.3.0, 3.3.1, 3.3.2].
    - magento/framework 102.0.4-p2 requires zendframework/zend-code ~3.3.0 -> satisfiable by laminas/laminas-code[3.3.0, 3.3.1, 3.3.2], zendframework/zend-code[3.3.0, 3.3.1, 3.3.2].
    - magento/framework 102.0.5 requires laminas/laminas-code ~3.3.0 -> satisfiable by laminas/laminas-code[3.3.0, 3.3.1, 3.3.2].
    - magento/framework 102.0.3-p1 requires zendframework/zend-code ~3.3.0 -> satisfiable by laminas/laminas-code[3.3.0, 3.3.1, 3.3.2], zendframework/zend-code[3.3.0, 3.3.1, 3.3.2].
    - magento/framework 102.0.4 requires zendframework/zend-code ~3.3.0 -> satisfiable by laminas/laminas-code[3.3.0, 3.3.1, 3.3.2], zendframework/zend-code[3.3.0, 3.3.1, 3.3.2].
    - magento/framework 102.0.3 requires zendframework/zend-code ~3.3.0 -> satisfiable by laminas/laminas-code[3.3.0, 3.3.1, 3.3.2], zendframework/zend-code[3.3.0, 3.3.1, 3.3.2].
    - Can only install one of: laminas/laminas-code[3.3.0, 3.4.1].
    - Can only install one of: laminas/laminas-code[3.3.1, 3.4.1].
    - Can only install one of: laminas/laminas-code[3.3.2, 3.4.1].
    - don't install zendframework/zend-code 3.3.0|don't install laminas/laminas-code 3.4.1
    - don't install zendframework/zend-code 3.3.1|don't install laminas/laminas-code 3.4.1
    - don't install zendframework/zend-code 3.3.2|don't install laminas/laminas-code 3.4.1
    - Installation request for laminas/laminas-code (locked at 3.4.1) -> satisfiable by laminas/laminas-code[3.4.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by jissereitsma** [comment]
Hi @rav-redchamps Thanks for trying this out. I've updated the `composer.json` file for Magento 2.4.1. Could you try again?

**Comment by rav-redchamps** [comment]
Hi @jissereitsma works now. Thanks for quick fix.
